name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Core
          user: raklaptudirm
          config_timezone: Asia/Calcutta
          committer_message: "chore: update metrics"
          
          # Display
          template: classic
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          
          plugin_languages: yes
          
          plugin_introduction: yes
          
          plugin_habits: yes
          
          plugin_licenses: yes
          
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          plugin_lines: yes
          
          plugin_activity: yes
          
          plugin_achievements: yes
          plugin_achievements_threshold: B
          
          plugin_notable: yes
          
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 14553594
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}        
          
